package fr.csf.ade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Mon Apr 12 16:11:34 CEST 2010
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://www.csf.fr/ade", name = "ParticulierSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ParticulierSoap {

    @WebResult(name = "getParticulierResult", targetNamespace = "http://www.csf.fr/ade")
    @RequestWrapper(localName = "getParticulier", targetNamespace = "http://www.csf.fr/ade", className = "fr.csf.ade.GetParticulier")
    @ResponseWrapper(localName = "getParticulierResponse", targetNamespace = "http://www.csf.fr/ade", className = "fr.csf.ade.GetParticulierResponse")
    @WebMethod(action = "http://www.csf.fr/ade/getParticulier")
    public fr.csf.ade.ParticulierData getParticulier(
        @WebParam(name = "numeroAdherent", targetNamespace = "http://www.csf.fr/ade")
        java.lang.String numeroAdherent
    );
}
