
/*
 * 
 */

package fr.csf.ade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.2
 * Mon Apr 12 16:11:34 CEST 2010
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "Particulier", 
                  wsdlLocation = "file:/D:/WORK/Workspaces/workspace-bpm/frameworkbpm/demo-cxf/src/main/wsdl/AdherentService.wsdl",
                  targetNamespace = "http://www.csf.fr/ade") 
public class Particulier extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.csf.fr/ade", "Particulier");
    public final static QName ParticulierHttpPost = new QName("http://www.csf.fr/ade", "ParticulierHttpPost");
    public final static QName ParticulierHttpGet = new QName("http://www.csf.fr/ade", "ParticulierHttpGet");
    public final static QName ParticulierSoap = new QName("http://www.csf.fr/ade", "ParticulierSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WORK/Workspaces/workspace-bpm/frameworkbpm/demo-cxf/src/main/wsdl/AdherentService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/WORK/Workspaces/workspace-bpm/frameworkbpm/demo-cxf/src/main/wsdl/AdherentService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Particulier(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Particulier(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Particulier() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ParticulierHttpPost
     */
    @WebEndpoint(name = "ParticulierHttpPost")
    public ParticulierHttpPost getParticulierHttpPost() {
        return super.getPort(ParticulierHttpPost, ParticulierHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParticulierHttpPost
     */
    @WebEndpoint(name = "ParticulierHttpPost")
    public ParticulierHttpPost getParticulierHttpPost(WebServiceFeature... features) {
        return super.getPort(ParticulierHttpPost, ParticulierHttpPost.class, features);
    }
    /**
     * 
     * @return
     *     returns ParticulierHttpGet
     */
    @WebEndpoint(name = "ParticulierHttpGet")
    public ParticulierHttpGet getParticulierHttpGet() {
        return super.getPort(ParticulierHttpGet, ParticulierHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParticulierHttpGet
     */
    @WebEndpoint(name = "ParticulierHttpGet")
    public ParticulierHttpGet getParticulierHttpGet(WebServiceFeature... features) {
        return super.getPort(ParticulierHttpGet, ParticulierHttpGet.class, features);
    }
    /**
     * 
     * @return
     *     returns ParticulierSoap
     */
    @WebEndpoint(name = "ParticulierSoap")
    public ParticulierSoap getParticulierSoap() {
        return super.getPort(ParticulierSoap, ParticulierSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParticulierSoap
     */
    @WebEndpoint(name = "ParticulierSoap")
    public ParticulierSoap getParticulierSoap(WebServiceFeature... features) {
        return super.getPort(ParticulierSoap, ParticulierSoap.class, features);
    }

}
